Repository eu-digital-identity-wallet/eudi-lib-jvm-siop-openid4vp-kt, pull requests merged in 2025-02, with the labels that each got.

#307 `transaction_data` support
  build.gradle.kts
  src/main/kotlin/eu/europa/ec/eudi/openid4vp/AuthorizationRequestResolver.kt
  src/main/kotlin/eu/europa/ec/eudi/openid4vp/Config.kt
  src/main/kotlin/eu/europa/ec/eudi/openid4vp/OpenId4VPSpec.kt
  src/main/kotlin/eu/europa/ec/eudi/openid4vp/Types.kt
  src/main/kotlin/eu/europa/ec/eudi/openid4vp/dcql/DCQL.kt
  src/main/kotlin/eu/europa/ec/eudi/openid4vp/internal/Base64.kt
  src/main/kotlin/eu/europa/ec/eudi/openid4vp/internal/Json.kt
  src/main/kotlin/eu/europa/ec/eudi/openid4vp/internal/request/DefaultAuthorizationRequestResolver.kt
  src/main/kotlin/eu/europa/ec/eudi/openid4vp/internal/request/RequestAuthenticator.kt
  src/main/kotlin/eu/europa/ec/eudi/openid4vp/internal/request/RequestObjectResolver.kt
  src/main/kotlin/eu/europa/ec/eudi/openid4vp/internal/request/RequestObjectValidator.kt
  src/main/kotlin/eu/europa/ec/eudi/openid4vp/internal/response/AuthorizationRequestErrorCode.kt
  src/test/kotlin/eu/europa/ec/eudi/openid4vp/UnvalidatedRequestResolverTest.kt
  src/test/kotlin/eu/europa/ec/eudi/openid4vp/dcql/DCQLParseTest.kt
  src/test/kotlin/eu/europa/ec/eudi/openid4vp/internal/request/WalletMetaDataTest.kt
  src/test/kotlin/eu/europa/ec/eudi/openid4vp/internal/response/AuthorizationResponseBuilderTest.kt
  src/test/kotlin/eu/europa/ec/eudi/openid4vp/internal/response/AuthorizationResponseDispatcherTest.kt
  src/test/kotlin/eu/europa/ec/eudi/openid4vp/internal/response/DefaultDispatcherTest.kt
Labels: feature, specification alignment, draft22

#309 Remove `state` parameter in case of `direct_post.jwt`, `query.jwt` and `fragment.jwt`
  src/main/kotlin/eu/europa/ec/eudi/openid4vp/internal/response/DefaultResponseDispatcher.kt
  src/test/kotlin/eu/europa/ec/eudi/openid4vp/Example.kt
  src/test/kotlin/eu/europa/ec/eudi/openid4vp/internal/response/DefaultDispatcherTest.kt
Labels: bug

#312 Add examples with SD-JWT-VC and Transaction Data
  src/test/kotlin/eu/europa/ec/eudi/openid4vp/Example.kt
  src/test/resources/example/mso_mdoc-pid-dcql-query.json
  src/test/resources/example/mso_mdoc-pid-presentation-definition.json
  src/test/resources/example/mso_mdoc_pid-deviceresponse.txt
  src/test/resources/example/sd-jwt-vc-pid-dcql-query.json
  src/test/resources/example/sd-jwt-vc-pid-key.json
  src/test/resources/example/sd-jwt-vc-pid-presentation-definition.json
  src/test/resources/example/sd-jwt-vc-pid.txt
Labels: feature
