Repository eu-digital-identity-wallet/eudi-lib-jvm-siop-openid4vp-kt, pull requests merged in 2025-03, with the labels that each got.

#325 Accept only `oauth-authz-req+jwt` as a type for JARs.
  src/main/kotlin/eu/europa/ec/eudi/openid4vp/OpenId4VPSpec.kt
  src/main/kotlin/eu/europa/ec/eudi/openid4vp/internal/request/RequestAuthenticator.kt
  src/test/kotlin/eu/europa/ec/eudi/openid4vp/UnvalidatedRequestResolverTest.kt
  src/test/kotlin/eu/europa/ec/eudi/openid4vp/internal/request/RequestAuthenticatorTest.kt
Labels: specification alignment, draft24

#330 Add missing `cty` header claim when the Payload of an Encrypted JWT is a Signed JWT
  src/main/kotlin/eu/europa/ec/eudi/openid4vp/internal/response/JarmJwt.kt
Labels: bug, specification alignment

#333 Improve client_metadata validation
  src/main/kotlin/eu/europa/ec/eudi/openid4vp/Types.kt
  src/main/kotlin/eu/europa/ec/eudi/openid4vp/internal/request/ClientMetaDataValidator.kt
  src/main/kotlin/eu/europa/ec/eudi/openid4vp/internal/request/ValidatedClientMetaData.kt
  src/main/kotlin/eu/europa/ec/eudi/openid4vp/internal/response/JarmJwt.kt
Labels: improvement

#331 Implement error dispatching
  README.md
  src/main/kotlin/eu/europa/ec/eudi/openid4vp/AuthorizationRequestResolver.kt
  src/main/kotlin/eu/europa/ec/eudi/openid4vp/Config.kt
  src/main/kotlin/eu/europa/ec/eudi/openid4vp/ErrorDispatcher.kt
  src/main/kotlin/eu/europa/ec/eudi/openid4vp/ResponseDispatcher.kt
  src/main/kotlin/eu/europa/ec/eudi/openid4vp/SiopOpenId4Vp.kt
  src/main/kotlin/eu/europa/ec/eudi/openid4vp/internal/request/ClientMetaDataValidator.kt
  src/main/kotlin/eu/europa/ec/eudi/openid4vp/internal/request/DefaultAuthorizationRequestResolver.kt
  src/main/kotlin/eu/europa/ec/eudi/openid4vp/internal/request/RequestAuthenticator.kt
  src/main/kotlin/eu/europa/ec/eudi/openid4vp/internal/request/RequestFetcher.kt
  src/main/kotlin/eu/europa/ec/eudi/openid4vp/internal/request/RequestObjectResolver.kt
  src/main/kotlin/eu/europa/ec/eudi/openid4vp/internal/response/AuthorizationResponse.kt
  src/main/kotlin/eu/europa/ec/eudi/openid4vp/internal/response/DefaultResponseDispatcher.kt
  src/main/kotlin/eu/europa/ec/eudi/openid4vp/internal/response/ErrorResponse.kt
  src/main/kotlin/eu/europa/ec/eudi/openid4vp/internal/response/JarmJwt.kt
  src/test/kotlin/eu/europa/ec/eudi/openid4vp/internal/response/AuthorizationResponseDispatcherTest.kt
Labels: feature, specification alignment

#338 Advertise missing 'vp_token id_token' response type.
  src/main/kotlin/eu/europa/ec/eudi/openid4vp/internal/request/WalletMetaData.kt
  src/test/kotlin/eu/europa/ec/eudi/openid4vp/internal/request/WalletMetaDataTest.kt
Labels: specification alignment

#341 Remove `jwks_uri` from Client Metadata
  src/main/kotlin/eu/europa/ec/eudi/openid4vp/AuthorizationRequestResolver.kt
  src/main/kotlin/eu/europa/ec/eudi/openid4vp/internal/request/ClientMetaDataValidator.kt
  src/main/kotlin/eu/europa/ec/eudi/openid4vp/internal/request/DefaultAuthorizationRequestResolver.kt
  src/main/kotlin/eu/europa/ec/eudi/openid4vp/internal/request/ValidatedClientMetaData.kt
  src/main/kotlin/eu/europa/ec/eudi/openid4vp/internal/response/AuthorizationRequestErrorCode.kt
  src/test/kotlin/eu/europa/ec/eudi/openid4vp/internal/request/ManagedClientMetaValidator.kt
  src/test/kotlin/eu/europa/ec/eudi/openid4vp/internal/response/AuthorizationResponseBuilderTest.kt
  src/test/kotlin/eu/europa/ec/eudi/openid4vp/internal/response/AuthorizationResponseDispatcherTest.kt
  src/test/kotlin/eu/europa/ec/eudi/openid4vp/internal/response/DefaultDispatcherTest.kt
Labels: specification alignment, draft22
