Repository eu-digital-identity-wallet/eudi-lib-jvm-siop-openid4vp-kt, pull requests merged in 2025-07, with the labels that each got.

#374 Add DC4EU EHIC example
  src/test/kotlin/eu/europa/ec/eudi/openid4vp/Example.kt
  src/test/resources/example/sd-jwt-vc-ehic-dcql-query.json
  src/test/resources/example/sd-jwt-vc-ehic-key.json
  src/test/resources/example/sd-jwt-vc-ehic.txt
Labels: other

#383 v1 updates for Client Id Prefix.
  Module.md
  README.md
  src/main/kotlin/eu/europa/ec/eudi/openid4vp/AuthorizationRequestResolver.kt
  src/main/kotlin/eu/europa/ec/eudi/openid4vp/Config.kt
  src/main/kotlin/eu/europa/ec/eudi/openid4vp/OpenId4VPSpec.kt
  src/main/kotlin/eu/europa/ec/eudi/openid4vp/Types.kt
  src/main/kotlin/eu/europa/ec/eudi/openid4vp/internal/request/RequestAuthenticator.kt
  src/main/kotlin/eu/europa/ec/eudi/openid4vp/internal/request/RequestObjectValidator.kt
  src/main/kotlin/eu/europa/ec/eudi/openid4vp/internal/request/WalletMetaData.kt
  src/main/kotlin/eu/europa/ec/eudi/openid4vp/internal/response/AuthorizationRequestErrorCode.kt
  src/test/kotlin/eu/europa/ec/eudi/openid4vp/Example.kt
  src/test/kotlin/eu/europa/ec/eudi/openid4vp/UnvalidatedRequestResolverTest.kt
  src/test/kotlin/eu/europa/ec/eudi/openid4vp/internal/request/RequestAuthenticatorTest.kt
  src/test/kotlin/eu/europa/ec/eudi/openid4vp/internal/request/RequestFetcherTest.kt
  src/test/kotlin/eu/europa/ec/eudi/openid4vp/internal/request/WalletMetaDataTest.kt
  src/test/kotlin/eu/europa/ec/eudi/openid4vp/internal/response/AuthorizationResponseBuilderTest.kt
  src/test/kotlin/eu/europa/ec/eudi/openid4vp/internal/response/AuthorizationResponseDispatcherTest.kt
  src/test/kotlin/eu/europa/ec/eudi/openid4vp/internal/response/DefaultDispatcherTest.kt
Labels: feature, specification alignment, v1, breaks public api

#392 Remove Ktor Factory
  README.md
  src/main/kotlin/eu/europa/ec/eudi/openid4vp/Ktor.kt
  src/main/kotlin/eu/europa/ec/eudi/openid4vp/SiopOpenId4Vp.kt
  src/main/kotlin/eu/europa/ec/eudi/openid4vp/internal/request/DefaultAuthorizationRequestResolver.kt
  src/main/kotlin/eu/europa/ec/eudi/openid4vp/internal/response/DefaultResponseDispatcher.kt
  src/test/kotlin/eu/europa/ec/eudi/openid4vp/Example.kt
  src/test/kotlin/eu/europa/ec/eudi/openid4vp/UnvalidatedRequestResolverTest.kt
  src/test/kotlin/eu/europa/ec/eudi/openid4vp/internal/response/AuthorizationResponseDispatcherTest.kt
  src/test/kotlin/eu/europa/ec/eudi/openid4vp/internal/response/DefaultDispatcherTest.kt
Labels: improvement, breaks public api

#401 Update Transaction Data
  src/main/kotlin/eu/europa/ec/eudi/openid4vp/AuthorizationRequestResolver.kt
  src/main/kotlin/eu/europa/ec/eudi/openid4vp/Config.kt
  src/main/kotlin/eu/europa/ec/eudi/openid4vp/Types.kt
  src/main/kotlin/eu/europa/ec/eudi/openid4vp/internal/request/RequestObjectValidator.kt
  src/test/kotlin/eu/europa/ec/eudi/openid4vp/Example.kt
  src/test/kotlin/eu/europa/ec/eudi/openid4vp/UnvalidatedRequestResolverTest.kt
  src/test/resources/dcql/complex_example.json
Labels: specification alignment, v1, breaks public api
