Repository eu-digital-identity-wallet/eudi-lib-jvm-siop-openid4vp-kt, pull requests merged in 2025-01, with the labels that each got.

#301 Remove `client_id_scheme`
  Module.md
  README.md
  src/main/kotlin/eu/europa/ec/eudi/openid4vp/AuthorizationRequestResolver.kt
  src/main/kotlin/eu/europa/ec/eudi/openid4vp/Config.kt
  src/main/kotlin/eu/europa/ec/eudi/openid4vp/OpenId4VPSpec.kt
  src/main/kotlin/eu/europa/ec/eudi/openid4vp/Types.kt
  src/main/kotlin/eu/europa/ec/eudi/openid4vp/internal/request/DefaultAuthorizationRequestResolver.kt
  src/main/kotlin/eu/europa/ec/eudi/openid4vp/internal/request/RequestAuthenticator.kt
  src/main/kotlin/eu/europa/ec/eudi/openid4vp/internal/response/AuthorizationResponse.kt
  src/main/kotlin/eu/europa/ec/eudi/openid4vp/internal/response/JarmJwt.kt
  src/test/kotlin/eu/europa/ec/eudi/openid4vp/SiopIdTokenBuilder.kt
  src/test/kotlin/eu/europa/ec/eudi/openid4vp/UnvalidatedRequestResolverTest.kt
  src/test/kotlin/eu/europa/ec/eudi/openid4vp/internal/request/RequestAuthenticatorTest.kt
  src/test/kotlin/eu/europa/ec/eudi/openid4vp/internal/response/DefaultDispatcherTest.kt
Labels: specification alignment, draft22

#303 Update README.md and Module.md
  Module.md
  README.md
Labels: documentation

#292 Draft22 - DCQL
  build.gradle.kts
  src/main/kotlin/eu/europa/ec/eudi/openid4vp/AuthorizationRequestResolver.kt
  src/main/kotlin/eu/europa/ec/eudi/openid4vp/Config.kt
  src/main/kotlin/eu/europa/ec/eudi/openid4vp/Format.kt
  src/main/kotlin/eu/europa/ec/eudi/openid4vp/OpenId4VPSpec.kt
  src/main/kotlin/eu/europa/ec/eudi/openid4vp/ResponseDispatcher.kt
  src/main/kotlin/eu/europa/ec/eudi/openid4vp/Types.kt
  src/main/kotlin/eu/europa/ec/eudi/openid4vp/dcql/ClaimPath.kt
  src/main/kotlin/eu/europa/ec/eudi/openid4vp/dcql/DCQL.kt
  src/main/kotlin/eu/europa/ec/eudi/openid4vp/internal/request/DefaultAuthorizationRequestResolver.kt
  src/main/kotlin/eu/europa/ec/eudi/openid4vp/internal/request/PresentationDefinitionResolver.kt
  src/main/kotlin/eu/europa/ec/eudi/openid4vp/internal/request/RequestAuthenticator.kt
  src/main/kotlin/eu/europa/ec/eudi/openid4vp/internal/request/RequestFetcher.kt
  src/main/kotlin/eu/europa/ec/eudi/openid4vp/internal/request/RequestObjectResolver.kt
  src/main/kotlin/eu/europa/ec/eudi/openid4vp/internal/request/RequestObjectValidator.kt
  src/main/kotlin/eu/europa/ec/eudi/openid4vp/internal/response/AuthorizationRequestErrorCode.kt
  src/main/kotlin/eu/europa/ec/eudi/openid4vp/internal/response/AuthorizationResponse.kt
  src/main/kotlin/eu/europa/ec/eudi/openid4vp/internal/response/DefaultResponseDispatcher.kt
  src/main/kotlin/eu/europa/ec/eudi/openid4vp/internal/response/JarmJwt.kt
  src/test/kotlin/eu/europa/ec/eudi/openid4vp/Example.kt
  src/test/kotlin/eu/europa/ec/eudi/openid4vp/UnvalidatedRequestResolverTest.kt
  src/test/kotlin/eu/europa/ec/eudi/openid4vp/dcql/DCQLParseTest.kt
  src/test/kotlin/eu/europa/ec/eudi/openid4vp/dcql/DCQLRulesTest.kt
  src/test/kotlin/eu/europa/ec/eudi/openid4vp/internal/response/AuthorizationResponseBuilderTest.kt
  src/test/kotlin/eu/europa/ec/eudi/openid4vp/internal/response/AuthorizationResponseDispatcherTest.kt
  src/test/kotlin/eu/europa/ec/eudi/openid4vp/internal/response/DefaultDispatcherTest.kt
  src/test/resources/dcql/basic_example.json
Labels: feature, specification alignment, draft22

#305 Update README.md and Module.md with information about DCQL.
  Module.md
  README.md
Labels: documentation, draft22
